#+title: Surround Source Code with UUID for Transclusion
#+date: {{{modification-time(%Y-%m-%d, VC)}}}
#+author: Steve Downey
#+email: sdowney@gmail.com
#+keywords:
#+language: en

#+org-export-with-smart-quotes: nil
#+org-export-with-emphasize: t
#+org-export-with-special-strings: t
#+org-export-with-fixed-width: t
#+org-export-with-timestamps: t
#+org-export-preserve-breaks: nil
#+org-export-with-sub-superscripts: nil
#+org-export-with-archived-trees: headline
#+org-export-with-author: t
#+org-export-headline-levels: 3

#+org-export-with-broken-links: nil
#+org-export-with-clocks: nil
#+org-export-with-creator: nil
#+org-export-with-drawers: (not "LOGBOOK")
#+org-export-with-date: t
#+org-export-with-entities: t

#+org-export-with-email: nil
#+org-export-with-footnotes: t
#+org-export-with-inlinetasks: t
#+org-export-with-section-numbers: t
#+org-export-with-planning: nil
#+org-export-with-priority: nil
#+org-export-with-properties: nil
#+org-export-with-statistics-cookies: t
#+org-export-with-tags: t

#+org-export-with-tasks: t
#+org-export-with-latex: t
#+org-export-timestamp-file: t
#+org-export-with-title: n
#+org-export-with-toc: nil
#+org-export-with-todo: t
#+org-export-with-tables: t

#+org-html-link-use-abs-url: nil
#+org-html-postamble: nil
#+org-html-preamble: t
#+org-html-scripts: n
#+org-html-style: nil
#+org-html5-fancy: t
#+org-html-self-link-headlines: t

#+html_doctype: xhtml5
#+html_container: div
#+html_link_home:
#+html_link_up:
#+html_mathjax:
#+html_head:
#+html_head_extra:
#+infojs_opt:

#+select_tags: export
#+exclude_tags: noexport

#+bibliography: ../references.bib
#+cite_export: csl

#+STARTUP: showall

* Surround Source Code with UUID for Transclusion

Surround the currently selected code with comments containing UUIDs that work as an org-link to use for [[https://github.com/nobiot/org-transclusion][nobiot's org-transclusion]]. The package provides two interactive functions -- ~uuid-surround-region-transclude~ and ~uuid-surround-region~ . The former puts the org-transclude statement into the kill ring for pasting into your org document. The latter just puts the comments in place, if you have some other mechanism for constructing the ~#+transclude ~.

The comment style is based on the mode of the current buffer. The comment will be placed at the beginning of the line containing the current region. The ending comment will be placed on the line after the current region, unless the ending line is blank, as defined by the syntax for the buffer.

** Before
#+begin_src C++
#include <print>

int main() {
  std::println("Hello, world!");
}
#+end_src

** After
#+begin_src C++
#include <print>

// 129c5ac0-442e-4bd5-b25d-6df372c0a4b5
int main() {
  std::println("Hello, world!");
}
// 129c5ac0-442e-4bd5-b25d-6df372c0a4b5 end
#+end_src

* Top Level Project

The overdone project infrastructure in the top-level project is to support GitHub CI and various bits of code quality. The CI is mostly driven by shell scripts in the .ci directory, which are borrowed from the [[https://github.com/emacs-exordium/exordium][Exordium Project]] and were written by [[https://github.com/pkryger][Przemysław Kryger]] who despaired of us breaking our shared emacs configuration. The [[https://github.com/pre-commit/pre-commit][pre-commit framework]] infrastructure is my fault, but helps me keep YAML less broken, and reduced the number of spelling mistakes and formatting errors. Running it automatically keeps me honest.

I have vendored in via ~git subtree~ the checkdoc code from pkryger as well.

More interesting may be the .minimal-emacs.d vendored in from [[https://github.com/jamescherti/minimal-emacs.d][James Cherti's minimal emacs.d project.]] This was of great use in making sure there was a lightweight but fully functional emacs configuration to run batch jobs from the command line, driven by a [[./Makefile][Makefile]].

* Example Project
This is the reason for the whole tiny bit of code.

I live in great fear of putting broken code up in a presentation.

I want to test it, somehow.

Using org-babel has turned out to be more cumbersome than I would like, so I was very happy to find org-transclude. I can make building my presentation dependent on the tests passing and extract the code snippets I want to show by marking up the actual compiled source. The project in the ~example~ directory is a complete C++ hello world project, and the results in example.md and example.html are output from org-export. The export can be run by ~make presentation~, which builds and runs the project and runs the org export. Although the dependencies are not quite right, yet.

This project also has overdone infrastructure, largely borrowed from the [[https://github.com/bemanproject][Beman Project]], reusing the infra from [[https://github.com/bemanproject/infra][bemanproject/infra]] and [[https://github.com/bemanproject/exemplar][bemanproject/exemplar]].
