name: CI Tests

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.gitignore'
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'

permissions:
  contents: read
  checks: write

jobs:
  ci-tests:
    runs-on: ${{ matrix.os }}
    env:
      ci_tests: true
    strategy:
      matrix:
        os:
          - ubuntu-latest
        emacs_version:
          - 29.4
          - 30.1
          - release-snapshot
          - snapshot
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # main
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          submodules: 'true'

      - uses: purcell/setup-emacs@bdc64dc730ae1fcba200bfd52cb1b4cf6159cbe5 # master
        with:
          version: ${{ matrix.emacs_version }}

      - name: 'Lint: checkdoc'
        run: |
                set -x
                .ci/batch-checkdoc.sh

      - name: 'Lint: compilation'
        # if: contains(fromJSON('["30.1", "snapshot", "release-snapshot"]'), matrix.emacs_version)
        run: |
                set -x
                .ci/batch-byte-compile.sh

      - name: 'Lint: flycheck' #  After compilation that should install all packages
        run: |
                set -x
                .ci//batch-flycheck.sh

      - name: 'Lint: relint'
        # if: contains(fromJSON('["30.1", "snapshot", "release-snapshot"]'), matrix.emacs_version)
        run: |
                set -x
                .ci//batch-relint.sh
